const hi = {
  app: { brandTop: "गैस्ट्रोनॉमिक", brandBottom: "क्यूज़ीन", nav: { dashboard: "डैशबोर्ड", generate: "जेनरेट", approval: "अनुमोदन", shopping: "खरीदारी", cook: "कुक", favorites: "फेवरिट्स" }, logout: "लॉगआउट", locale: "भाषा" },
  common: { mealFallback: "सेवा", noDate: "सेवा समय उपलब्ध नहीं", ready: "तैयार", noData: "कोई डेटा नहीं", table: { menu: "मेनू", meal: "भोजन", service: "सेवा", updated: "अपडेट", generated: "जनरेट", readiness: "तैयारी", items: "आइटम", progress: "प्रगति" } },
  dashboard: { eyebrow: "Executive kitchen operations", title: "Design world-class dining moments from one premium workspace", description: "Generate Michelin-level menus, orchestrate invitee consensus, and execute service with confidence across every station.", today: "Today", workflowHealthy: "Workflow healthy", snapshot: "6 invitees · 3 curated options · 1 final service", chips: { hospitality: "Luxury Hospitality", ai: "AI Culinary Intelligence", clarity: "Enterprise Clarity" }, pillars: { generationTitle: "Menu Generation", generationText: "AI-orchestrated tasting options with refined culinary language and premium service cues.", approvalTitle: "Approval Intelligence", approvalText: "Tokenized voting with clear leadership signals, invitee sentiment, and decision confidence.", operationsTitle: "Operational Mastery", operationsText: "Shopping, prep, and service timelines translated into executive-grade culinary execution." } },
  generate: { eyebrow: "Flagship Experience", title: "Generate an extraordinary Michelin-style service", description: "Combine context, constraints, and flavor direction to produce cinematic menu options for your next event.", form: { title: "Compose a signature service", description: "Design a cinematic dining journey with structured constraints, guest context, and a luxurious final reveal.", mealType: "Meal Type", courseCount: "Course Count", courses: "courses", guestCount: "Guest count", serviceTime: "Service Time", scheduledFor: "Scheduled for", chefNotes: "Chef Notes", chefNotesPlaceholder: "Desired produce, preferred regions, plating cues, or thematic inspiration.", restrictionsPerIndividual: "Restrictions per individual", uniqueRestrictions: "unique restrictions", label: "Label", firstNameOptional: "First name (optional)", firstNameExample: "e.g. Ana", generating: "Generating luxurious options...", generateOptions: "Generate 3 curated options", optionsGenerated: "options generated" } },
  approval: { eyebrow: "Approval Intelligence", title: "Approved menus", description: "Review approved services, open full menu details, and remove cancelled plans safely.", empty: "No approved menus yet. Select an option on Generate to approve it.", selectedOption: "Selected option", stats: { approved: "Approved", validated: "Validated", leader: "Leader" }, optionSelected: "Option selected", pending: "Pending", deleteSelected: "Delete selected", selectAll: "Select all menus", invitees: "Invitees", status: "Status", deleteError: "Failed to delete approved menus.", deleteConfirm: "Delete selected approved menus? This cannot be undone.", selectMenu: "Select menu", detail: { eyebrow: "Approved Service", menuMetadata: "Menu metadata", restrictions: "Restrictions", none: "None", chefNotes: "Chef notes", noChefNotes: "No chef notes", selectedOption: "Selected option", approvedOption: "Approved option", noConceptSummary: "No concept summary.", beveragePairing: "Beverage pairing", notSpecified: "Not specified", optionChefNotes: "Option chef notes", noOptionNotes: "No option notes", menuHero: "Menu hero", dishes: "Dishes", course: "Course", plating: "Plating", noPlatingNotes: "No plating notes", decoration: "Decoration", noDecorationNotes: "No decoration notes", noDishes: "No dishes available for the approved option.", cookingGuidance: "Cooking guidance", noCookOverview: "No cook overview yet.", notGenerated: "Not generated", platingOverview: "Plating overview", shoppingListStatus: "Shopping list status", itemsPrepared: "items prepared", notGeneratedYet: "Not generated yet" } },
  shopping: { eyebrow: "Operations", title: "Shopping intelligence", description: "Track procurement progress with premium operational clarity and move directly into cooking execution.", empty: "No shopping lists yet. Open an approved menu and generate one.", detail: { eyebrow: "Operational Workspace", notGenerated: "Shopping list not generated yet. Open this menu from Approval and click ‘Shopping List’.", menuContext: "Menu context" } },
  favorites: { eyebrow: "Curated Archive", title: "Favorites, refined and collectible", description: "Revisit top-rated menus and relaunch memorable gastronomic experiences with one click.", people: "people", unspecifiedDate: "unspecified date", guestSentiment: "Guest sentiment", rating: "rating", empty: "No favorites yet. Menus are added after feedback scores are high." },
  cook: { heroEyebrow: "सर्विस टाइमलाइन", indexTitle: "कुक-रेडी सर्विस", indexDescription: "जिन मेनू के लिए कुक प्लान बना है वे यहाँ दिखेंगे।", noPlans: "अभी कोई कुक प्लान नहीं है। प्लान बनाने के लिए मेनू वैलिडेट करें।", noPlanForMenu: "इस मेनू के लिए अभी कुक प्लान नहीं है।", overview: "ओवरव्यू", timeline: "कुक टाइमलाइन", plating: "प्लेटिंग", serviceNotes: "सर्विस नोट्स", miseEnPlace: "मिज़-ऑन-प्लास", noOverview: "ओवरव्यू उपलब्ध नहीं।", noMise: "मिज़-ऑन-प्लास गाइड नहीं।", noPlating: "प्लेटिंग ओवरव्यू नहीं।", noServiceNotes: "सर्विस नोट्स नहीं।", noSteps: "कोई स्टेप नहीं बना।", dish: "डिश", step: "स्टेप", objective: "उद्देश्य", duration: "अवधि", tools: "उपकरण", warning: "चेतावनी" }
};
export default hi;
